<h3> A Neural Network Implementation for Pattern Classification using Hebb's rule </h3>

<b>Reading input images </b>

In [1]:
import numpy as np
import os

In [2]:
filePath = "./pattern_data/"

In [3]:
def read_file(fileName):
    file = os.path.join(filePath,fileName)
    print('Quering file {}'.format(file))
    
    pattern, labels,pixel =[],[],[];
    with open(file,"r") as f:
        lines = f.read().splitlines()
        for line in lines:
            for ch in line:
                if ch == "#" or ch == ".":
                    pixel.append(ch)
                elif ch ==",":
                    pattern.append(pixel)
                    pixel=[]
                else:
                    labels.append(ch)
            
    print('..Completed processing file..."')
    return pattern, labels
    
    
    
    

In [4]:
train_patterns,train_labels = read_file(fileName="training_data.txt")

Quering file ./pattern_data/training_data.txt
..Completed processing file..."


In [5]:
test_patterns,test_labels = read_file(fileName="test_data.txt")


Quering file ./pattern_data/test_data.txt
..Completed processing file..."


In [6]:
def convertPatternToBipolarVectors(patterns):
    input_vector,image = [],[];
    for pattern in patterns:
        for  ch in pattern:
            if ch == "#":
                image.append(-1)
            elif ch == ".":
                image.append(1)
                
        input_vector.append(image)
        image=[]
        
    return input_vector

def convertLabelToBipolar(labels):
    output_vector =[];
    
    for ch in labels:
        if ch == "C":
            output_vector.append(1)
        else:
            output_vector.append(-1)

    return output_vector
            

In [7]:
bipolar_train = convertPatternToBipolarVectors(train_patterns)
bipolar_train_label = convertLabelToBipolar(train_labels)

In [8]:
bipolar_test = convertPatternToBipolarVectors(test_patterns)

In [9]:
def convertTrainToNumpyArray(data,labels):
    images = np.array(data)
    dim = labels[0]
    t = np.array(labels).reshape(-1,dim)
    return images,t

def convertTestToNumpyArray(data):
    images = np.array(data)
    return images


In [10]:
patterns_train,t = convertTrainToNumpyArray(bipolar_train,bipolar_train_label)

In [11]:
print('Training Images dimensions',patterns_train.shape)
print('Training Labels dimensions',t.shape)

Training Images dimensions (2, 15)
Training Labels dimensions (2, 1)


In [12]:
patterns_test = convertTestToNumpyArray(bipolar_test)

In [13]:
print('Testing Images dimensions',patterns_test.shape)

     

Testing Images dimensions (14, 15)


<b>Define the dimensions for a two layered  Neural Network Perceptron Model</b>

In [14]:

dimensions = [patterns_train.shape[1],t.shape[1]]
parameters = {}


Define the Neural Network

In [15]:
class NeuralNetwork:
    def __init__(self,dimensions):
        self.parameters = parameters
        
        print('...Initializing Parameters for the model...')
        parameters["W"] = np.zeros([dimensions[0],dimensions[1]])
        parameters["b"] = np.zeros([dimensions[1],1])
        
        #print('Weight Matrix defined as {}'.format(parameters["W"].shape))
        #print('Bias Vector defined as {}'.format(parameters["b"].shape))
        
    def affineForward(self,X,W,b):
        print('.....Staring affineForward.....')
        yin = np.dot(X,W) + b      
        #print(yin)
        return yin
    
    def feedForwardPropagation(self,X):
        print('....Start FeedForwardPropagation....')
        
        W = self.parameters["W"]
        b = self.parameters["b"]
        yin = self.affineForward(X,W,b)
        
        #print ('Shape of output {}'.format(yin.shape))
        return yin
    
    def backwardPropagation(self,t,S):
        print('....Starting backpropagation.....')
        dw = np.dot(S.T,t)
        db = np.sum(t,axis=0).reshape(1,-1)
        #print('Delta W:{}'.format(dw.shape))
        #print('Delta b:{}'.format(db.shape))
        return dw,db
    
    def updateParameters(self,dw,db):
        print('....Updating Weight and bias.....')
        parameters = self.parameters
        
        parameters["W"] = np.add(parameters["W"],dw)
        parameters["b"] = np.add(parameters["b"],db)
        
        
    def train(self,X,t,numOfIterations):
        S = X
        y = t
        print('......Training Data Model......')
        for i in range(1,numOfIterations):
            print('Starting iteration {}....'.format(i))
            yin = self.feedForwardPropagation(X)
            dw,db = self.backwardPropagation(y,S)
            self.updateParameters(dw,db)
        
        print('...Training ends here....')
        
     
    def predict(self,X):
        t = self.feedForwardPropagation(X)
        return t

In [16]:
model = NeuralNetwork(dimensions)


...Initializing Parameters for the model...


In [17]:
model.train(patterns_train,t,4)

......Training Data Model......
Starting iteration 1....
....Start FeedForwardPropagation....
.....Staring affineForward.....
....Starting backpropagation.....
....Updating Weight and bias.....
Starting iteration 2....
....Start FeedForwardPropagation....
.....Staring affineForward.....
....Starting backpropagation.....
....Updating Weight and bias.....
Starting iteration 3....
....Start FeedForwardPropagation....
.....Staring affineForward.....
....Starting backpropagation.....
....Updating Weight and bias.....
...Training ends here....


In [18]:
t_pred = model.predict(patterns_test)

....Start FeedForwardPropagation....
.....Staring affineForward.....


In [19]:
t_pred

array([[ 48.],
       [ 36.],
       [ 36.],
       [ 36.],
       [ 24.],
       [ 12.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [-12.],
       [-24.],
       [-36.],
       [-36.]])

In [20]:
t_pred = list(t_pred)

In [22]:
output = [ v for v in t_pred if v > 0]

In [23]:
output

[array([48.]),
 array([36.]),
 array([36.]),
 array([36.]),
 array([24.]),
 array([12.])]